import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from '@/component/navigation'
import { getShows } from '@/api/content';
import { kebabCase } from '@/utility/kebab';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const shows = await getShows()

  const showsList = shows.map((show) => ({
    id: kebabCase(show.fields.title),
    title: show.fields.title
  }))

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation shows={showsList}></Navigation>
        {children}
      </body>
    </html>
  )
}
